# **Importing the Libraries**

In [1]:
import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import plotly.figure_factory as ff
import plotly
from plotly.offline import plot, iplot
import warnings
warnings.filterwarnings('ignore')

# **Importing the dataset**

In [2]:
dataset = pd.read_csv("../input/ipl-player-auction-dataset-from-start-to-now/IPLPlayerAuctionData.csv")
dataset

,Player,Role,Amount,Team,Year,Player Origin
0,Aaron Finch,Batsman,40000000,Sunrisers Hyderabad,2014.0,Overseas
1,Aaron Finch,Batsman,32000000,Mumbai Indians,2015.0,Overseas
2,Aaron Finch,Batsman,10000000,Gujarat Lions,2016.0,Overseas
3,Aaron Finch,Batsman,62000000,Kings XI Punjab,2018.0,Overseas
4,Aaron Finch,Batsman,44000000,Royal Challengers Bangalore,2020.0,Overseas
...,...,...,...,...,...,...
965,Yuzvendra Singh Chahal,Bowler,1000000,Royal Challengers Bangalore,2014.0,Indian
966,Yuzvendra Singh Chahal,Bowler,60000000,Royal Challengers Bangalore,2018.0,Indian
967,Zaheer Khan,Bowler,26000000,Mumbai Indians,2014.0,Indian
968,Zaheer Khan,Bowler,40000000,Delhi Daredevils,2015.0,Indian
969,Zahir Khan Pakteen,Bowler,6000000,Rajasthan Royals,2018.0,Indian

# **Data Wrangling**

In [3]:
dataset.head()

,Player,Role,Amount,Team,Year,Player Origin
0,Aaron Finch,Batsman,40000000,Sunrisers Hyderabad,2014.0,Overseas
1,Aaron Finch,Batsman,32000000,Mumbai Indians,2015.0,Overseas
2,Aaron Finch,Batsman,10000000,Gujarat Lions,2016.0,Overseas
3,Aaron Finch,Batsman,62000000,Kings XI Punjab,2018.0,Overseas
4,Aaron Finch,Batsman,44000000,Royal Challengers Bangalore,2020.0,Overseas

In [4]:
dataset.tail()

,Player,Role,Amount,Team,Year,Player Origin
965,Yuzvendra Singh Chahal,Bowler,1000000,Royal Challengers Bangalore,2014.0,Indian
966,Yuzvendra Singh Chahal,Bowler,60000000,Royal Challengers Bangalore,2018.0,Indian
967,Zaheer Khan,Bowler,26000000,Mumbai Indians,2014.0,Indian
968,Zaheer Khan,Bowler,40000000,Delhi Daredevils,2015.0,Indian
969,Zahir Khan Pakteen,Bowler,6000000,Rajasthan Royals,2018.0,Indian

In [5]:
dataset.describe()

             Amount         Year
count  9.700000e+02   969.000000
mean   2.105451e+07  2017.910217
std    2.800091e+07     2.964527
min    1.000000e+06  2013.000000
25%    2.000000e+06  2015.000000
50%    9.500000e+06  2018.000000
75%    3.000000e+07  2021.000000
max    1.625000e+08  2022.000000

In [6]:
dataset.columns

Index(['Player', 'Role', 'Amount', 'Team', 'Year', 'Player Origin'], dtype='object')

In [7]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 970 entries, 0 to 969
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Player         970 non-null    object
 1   Role           970 non-null    object
 2   Amount         970 non-null    int64
 3   Team           970 non-null    object
 4   Year           969 non-null    float64
 5   Player Origin  970 non-null    object
dtypes: float64(1), int64(1), object(4)
memory usage: 45.6+ KB

In [8]:
dataset.shape

(970, 6)

In [9]:
dataset.keys()

Index(['Player', 'Role', 'Amount', 'Team', 'Year', 'Player Origin'], dtype='object')

In [10]:
dataset.describe(include="all")

,Player,Role,Amount,Team,Year,Player Origin
count,970,970,9.700000e+02,970,969.000000,970
unique,543,4,NaN,15,NaN,2
top,Jaydev Unadkat,Bowler,NaN,Royal Challengers Bangalore,NaN,Indian
freq,9,352,NaN,115,NaN,616
mean,NaN,NaN,2.105451e+07,NaN,2017.910217,NaN
std,NaN,NaN,2.800091e+07,NaN,2.964527,NaN
min,NaN,NaN,1.000000e+06,NaN,2013.000000,NaN
25%,NaN,NaN,2.000000e+06,NaN,2015.000000,NaN
50%,NaN,NaN,9.500000e+06,NaN,2018.000000,NaN
75%,NaN,NaN,3.000000e+07,NaN,2021.000000,NaN
max,NaN,NaN,1.625000e+08,NaN,2022.000000,NaN

In [11]:
dataset.isnull().sum()

Player           0
Role             0
Amount           0
Team             0
Year             1
Player Origin    0
dtype: int64

**Removing the row where year is null**

In [12]:
dataset.dropna(inplace=True)

Converting the data type of Year's column from float to int

In [13]:
dataset.Year = dataset.Year.apply(int)

In [14]:
print(f"Dataset contains data of \033[1m{dataset.Player.unique().size}\033[0m Players")
dataset.Player.unique()

Dataset contains data of 543 Players

array(['Aaron Finch', 'Abdul Samad', 'Abhijeet Tomar', 'Abhimanyu Mithun',
       'Abhinav Sadarangani', 'Abhishek Nayar', 'Abhishek Sharma',
       'Abu Nechim Ahmed', 'Adam Milne', 'Adam Zampa', 'Aditya Garhwal',
       'Aditya Tare', 'Agnivesh Ayachi', 'Aiden Blizzard',
       'Aiden Markram', 'Ajantha Mendis', 'Ajinkya Rahane', 'Akash Deep',
       'Akash Singh', 'Akhil Arvind Herwadkar', 'Akila Dananjaya',
       'Akila Dhananjaya', 'Akshar Rajesh Patel', 'Akshay Karnewar',
       'Akshay Wakhare', 'Akshdeep Nath', 'Albie Morkel', 'Alex Carey',
       'Alex Hales', 'Alzarri Joseph', 'Aman Khan', 'Ambati Rayudu',
       'Amit Mishra', 'Amit Paunikar', 'Andre Russell', 'Andrew Tye',
       'Aneeshwar Gautam', 'Angelo Mathews', 'Aniket Choudhary',
       'Anirudha Ashok Joshi', 'Ankeet Bawane', 'Ankit Nagendra Sharma',
       'Ankit Sharma', 'Ankit Singh Rajpoot', 'Ankush Bains',
       'Anmolpreet Singh', 'Anrich Nortje', 'Ansh Patel', 'Anuj Rawat',
       'Anukul Roy', 'Anunay Singh', 'Anureet Singh',
       'Apoorv Vijay Wankhade', 'Arjun Tendulkar', 'Armaan Jaffer',
       'Arshdeep Singh', 'Aryaman Vikram Birla', 'Aryan Juyal',
       'Asela Gunarathna', 'Ashish Nehra', 'Ashish Reddy', 'Ashok Dinda',
       'Ashok Sharma', 'Ashton Turner', 'Ashwin Hebbar', 'Asif K M',
       'Atharva Taide', 'Avesh Khan', 'Axar Rajesh Patel', 'Ayush Badoni',
       'B. Sai Sudharsan', 'Baba Aparajith', 'Baba Indrajith',
       'Baltej Dhanda', 'Bandaru Ayyappa', 'Barinder Singh Saran',
       'Barinder Singh Sran', 'Basil Thampi', 'Ben Cutting', 'Ben Dunk',
       'Ben Dwarshuis', 'Ben Hilfenhaus', 'Ben Laughlin',
       'Benjamin Stokes', 'Benny Howell', 'Beuran Hendricks',
       'Bhanuka Rajapaksa', 'Bhuvneshwar Kumar', 'Billy Stanlake',
       'Bipul Sharma', 'Brad Hodge', 'Brad Hogg', 'Brendan Taylor',
       'Brendon McCullum', 'C Hari Nishaanth', 'C.Hari Nishaanth',
       'C.M. Gautam', 'Cameron Delport', 'Carlos Brathwaite',
       'Chaitanya Bishnoi', 'Chama Milind', 'Chamika Karunaratne',
       'Chetan Sakariya', 'Cheteshwar Pujara', 'Chirag Suri',
       'Chris Green', 'Chris Jordan', 'Chris Lynn', 'Chris Woakes',
       'Christopher Barnwell', 'Christopher Gayle', 'Christopher Morris',
       'Clinton McKay', 'Colin De Grandhomme', 'Colin Ingram',
       'Colin Munro', 'Corey Anderson', 'Dale Steyn', 'Dan Christian',
       'Daniel Christian', 'Daniel Sams', 'Darcy Short', 'Darren Bravo',
       'Darren Sammy', 'Darshan Nalkande', 'Daryl Mitchell',
       'David Miller', 'David Warner', 'David Wiese', 'David Willey',
       'Dawid Malan', 'Debabrata Das', 'Deepak Chahar', 'Deepak Hooda',
       'Deepak Punia', 'Devdutt Padikkal', 'Devon Conway',
       'Dewald Brevis', 'Dhawal Kulkarni', 'Dhruv Jurel', 'Dhruv Shorey',
       'Digvijay Deshmukh', 'Dinesh Karthik', 'Dinesh Salunkhe',
       'Dirk Nannes', 'Dishant Yagnik', 'Dominic Drakes',
       'Domnic Joseph Muthuswamy', 'Dushmanta Chameera',
       'Dushmantha Chameera', 'Dwaine Pretorius', 'Dwayne Bravo',
       'Dwayne Smith', 'Eklavya Dwivedi', 'Eoin Morgan', 'Evin Lewis',
       'Fabian Allen', 'Faf Du Plessis', 'Farhaan Behardien',
       'Fazalhaq Farooqi', 'Fidel Edwards', 'Finn Allen',
       'Gautam Gambhir', 'George Bailey', 'Glenn Maxwell',
       'Glenn Phillips', 'Gurinder Sandhu', 'Gurkeerat Singh Mann',
       'Hanuma Vihari', 'Harbhajan Singh', 'Hardik Pandya',
       'Hardus Viljoen', 'Harpreet Brar', 'Harry Gurney', 'Harshal Patel',
       'Heinrich Klaasen', 'Himmat Singh', 'Hrithik Shokeen',
       'HS Sharath', 'Imran Tahir', 'Iqbal Abdullah', 'Irfan Pathan',
       'Ishan Kishan', 'Ishan Porel', 'Ishank Jaggi', 'Ishant Sharma',
       'Ishwar Chandra Pandey', 'Isuru Udana', 'J Suchith', 'Jacob Oram',
       'Jacques Kallis', 'Jagadeesha Suchith', 'Jalaj Saxena',
       'James Faulkner', 'James Neesham', 'Jaskaran Singh',
       'Jason Behrendorff', 'Jason Holder', 'Jason Roy', 'Jasprit Bumrah',
       'Jatin Saxena', 'Javon Searless', 'Jayant Yadav', 'Jaydev Shah',
       'Jaydev Unadkat', 'Jean-Paul Duminy', 'Jeevan Mendis',
       'Jesse Ryder', 'Jhye Richardson', 'Jitesh Sharma', 'Joe Denly',
       'Joel Paris', 'Jofra Archer', 'Johan Botha', 'John Hastings',
       'Jonny Bairstow', 'Jos Buttler', 'Josh Hazlewood',
       'Joshua Philippe', 'Juan Theron', 'Krishnappa Gowtham',
       'K.Bhagath Varma', 'K.C Cariappa', 'K.C. Cariappa', 'K.K. Jiyaz',
       'K.M. Asif', 'K.S. Bharat', 'Kagiso Rabada', 'Kamlesh Nagarkoti',
       'Kane Richardson', 'Kane Williamson', 'Kanishk Seth',
       'Karan Sharma', 'Karanveer Singh', 'Karn Sharma', 'Kartik Tyagi',
       'Karun Nair', 'Kedar Jadhav', 'Keemo Paul', 'Kevin Pietersen',
       'Kevon Cooper', 'Kieron Pollard', 'Kishore Pramod Kamath',
       'KL Rahul', 'Kona Srikar Bharat', 'Krismar Santokie',
       'Krunal Pandya', 'Kshitiz Sharma', 'Kuldeep Sen', 'Kuldeep Yadav',
       'Kuldip Yadav', 'Kulwant Khejroliya', 'Kusal Janith Perera',
       'Kyle Abbott', 'Kyle Jamieson', 'Kyle Mayers',
       'Lakshmipathy Balaji', 'Lalit Yadav', 'Lasith Malinga',
       'Laxmi Ratan Shukla', 'Liam Livingstone', 'Lockie Ferguson',
       'Luke Pomersbach', 'Lukman Hussain Meriwala', 'Lungisani Ngidi',
       'Luvnith Sisodia', 'M Siddharth', 'M. Ashwin',
       'M. Harisankar Reddy', 'Washington Sundar', 'Maheesh Theekshana',
       'Mahipal Lomror', 'Manan Ajay Sharma', 'Manan Vohra',
       'Mandeep Hardev Singh', 'Mandeep Singh', 'Manish Pandey',
       'Manjot Kalra', 'Manoj Tiwary', 'Manpreet Gony', 'Manprit Juneja',
       'Manvinder Bisla', 'Manzoor Dar', 'Marchant De Lange',
       'Marco Jansen', 'Marcus Stoinis', 'Mark Wood', 'Martin Guptill',
       'Matt Henry', 'Matthew Wade', 'Mayank Agarwal', 'Mayank Dagar',
       'Mayank Markande', 'Mayank Yadav', 'Michael Clarke',
       'Michael Hussey', 'Midhun S', 'Milind Kumar', 'Milind Tandon',
       'Mitchell Johnson', 'Mitchell Marsh', 'Mitchell McClenaghan',
       'Mitchell Santner', 'Mitchell Starc', 'Mithun Manhas', 'Moeen Ali',
       'Mohammad Nabi', 'Mohammad Shami', 'Mohammed Azharudeen',
       'Mohammed Siraj', 'Mohd. Arshad Khan', 'Mohit Sharma',
       'Mohsin Khan', 'Moises Henriques', 'Monu Singh', 'Morne Morkel',
       'Mujeeb Zadran', 'Mukesh Choudhary', 'Munaf Patel',
       'Murali Kartik', 'Murali Vijay', 'Murugan Ashwin',
       'Mustafizur Rahman', 'Muttiah Muralitharan', 'N Jagadeesan',
       'N. Jagadeesan', 'N. Tilak Varma', 'Naman Ojha',
       'Nathan Coulter-Nile', 'Nathan Ellis', 'Nathan McCullum',
       'Nathu Singh', 'Navdeep Saini', 'Nic Maddinson', 'Nicolas Pooran',
       'Nidheesh M D Dinesan', 'Nikhil Shankar Naik', 'Nitish Rana',
       'Noor Ahmad', 'Obed Mccoy', 'Odean Smith', 'Oshane Thomas',
       'Pankaj Jaswal', 'Pankaj Singh', 'Paras Dogra', 'Pardeep Sahu',
       'Parthiv Patel', 'Parveez Rasool', 'Parvinder Awana',
       'Pat Cummins', 'Pavan Deshpande', 'Pawan Negi', 'Pawan Suyal',
       'Peter Handscomb', 'Philip Hughes', 'Piyush Chawla',
       'Prabhsimran Singh', 'Pradeep Sangwan', 'Pragyan Ojha',
       'Prasanth Padmanabhan', 'Prasanth Parameswaran', 'Prashant Chopra',
       'Prashant Solanki', 'Prasidh Krishna', 'Pratham Singh',
       'Pratyush Singh', 'Praveen Dubey', 'Praveen Kumar', 'Pravin Dubey',
       'Pravin Tambe', 'Prayas Ray Barman', 'Prerak Mankad',
       'Prince Balwant Rai Singh', 'Prithvi Raj Yarra', 'Prithvi Shaw',
       'Priyam Garg', 'Quinton De Kock', 'R Samarth', 'R. Ashwin',
       'R. Sai Kishore', 'R. Sanjay Yadav', 'Rahul Ajay Tripathi',
       'Rahul Buddhi', 'Rahul Chahar', 'Rahul Sharma', 'Rahul Shukla',
       'Rahul Tewatia', 'Rahul Tripathi', 'Raj Angad Bawa',
       'Rajagopal Sathish', 'Rajat Bhatia', 'Rajat Patidar',
       'Rajvardhan Hangargekar', 'Ramandeep Singh', 'Ramesh Kumar',
       'Ranganath Vinay Kumar', 'Rashid Khan Arman', 'Rasikh Dar',
       'Rassie Van Der Dussen', 'Ravi Bishnoi', 'Ravi Bopara',
       'Ravi Rampaul', 'Ravichandran Ashwin', 'Ricky Bhui',
       'Ricky Ponting', 'Riley Meredith', 'Rinku Singh', 'Ripal Patel',
       'Rishabh Pant', 'Rishi Dhawan', 'Riyan Parag', 'Robin Uthappa',
       'Romario Shepherd', 'Ronit More', 'Ross Taylor', 'Rovman Powell',
       'Rudra Pratap Singh', 'Ruturaj Gaikwad', 'Ryan McLaren',
       'Ryan Ten Doeschate', 'Sachin Baby', 'Sachin Rana',
       'Sachithra Senanayaka', 'Sagar Trivedi', 'Sam Billings',
       'Sam Curran', 'Samuel Badree', 'Sandeep Bavanaka',
       'Sandeep Lamichhane', 'Sandeep Sharma', 'Sandeep Warrier',
       'Sanjay Yadav', 'Sanju Samson', 'Sarabjit Ladda', 'Sarfaraz Khan',
       'Sarfaraz Naushad Khan', 'Saurabh Dubey', 'Saurabh Kumar',
       'Saurabh Tiwary', 'Sayan Ghosh', 'Sayan Sekhar Mandal',
       'Scott Boland', 'Sean Abbott', 'Shadab Jakati', 'Shahbaz Ahamad',
       'Shahbaz Nadeem', 'Shahrukh Khan', 'Shakib Al Hasan',
       'Shane Watson', 'Sharad Lumba', 'Shardul Thakur', 'Shashank Singh',
       'Shaun Marsh', 'Sheldon Cottrell', 'Sheldon Jackson',
       'Shelley Shaurya', 'Sherfane Rutherford', 'Shikhar Dhawan',
       'Shimron Hetmyer', 'Shishir Bhavane', 'Shivam Dube', 'Shivam Mavi',
       'Shivam Sharma', 'Shivil Kaushik', 'Shreevats Goswami',
       'Shreyas Gopal', 'Shreyas Iyer', 'Shrikant Mundhe',
       'Shubam Agrawal', 'Shubham Garhwal', 'Shubham Ranjane',
       'Shubman Gill', 'Siddarth Kaul', 'Siddharth Kaul',
       'Siddhesh Dinesh Lad', 'Simarjeet Singh', 'Srikkanth Anirudha',
       'Steven Smith', 'Stuart Binny', 'Subhranshu Senapati',
       'Subramaniam Badrinath', 'Sudeep Tyagi', 'Sumit Narwal',
       'Suryakumar Yadav', 'Sushant Marathe', 'Suyash Prabhudesai',
       'Suyash Prabhudessai', 'Swapnil Singh', 'Syed Khaleel Ahmed',
       'Syed Mehdi Hasan', 'T Natarajan', 'T. Natarajan',
       'Tajinder Dhillon', 'Tanmay Agarwal', 'Tanmay Mishra',
       'Tejas Baroka', 'Tejas Singh Baroka', 'Thisara Perera',
       'Tim David', 'Tim Seifert', 'Tim Southee', 'Tirumalasetti Suman',
       'Tom Banton', 'Tom Curran', 'Travis Head', 'Trent Boult',
       'Tushar Deshpande', 'Tymal Mills', 'Umang Sharma', 'Umesh Yadav',
       'Unmukt Chand', 'Utkarsh Singh', 'Vaibhav Arora', 'Vaibhav Rawal',
       'Varun Aaron', 'Varun Chakaravarthy', 'Veer Pratap Singh',
       'Venkatesh Iyer', 'Venugopal Rao', 'Vicky Ostwal', 'Vijay Shankar',
       'Vijay Zol', 'Vikas Tokas', 'Vikramjeet Malik', 'Virat Singh',
       'Virender Sehwag', 'Vishnu Vinod', 'Wanindu Hasaranga',
       'Wayne Parnell', 'Wriddhiman Saha', 'Writtick Chatterjee',
       'Yash Dayal', 'Yash Dhull', 'Yashasvi Jaiswal', 'Yogesh Gowalkar',
       'Yogesh Takawale', 'Yudhvir Charak', 'Yusuf Pathan',
       'Yuvraj Singh', 'Yuzvendra Chahal', 'Yuzvendra Singh Chahal',
       'Zaheer Khan', 'Zahir Khan Pakteen'], dtype=object)

In [15]:
print(f"Dataset contains data of \033[1m{dataset.Role.unique().size}\033[0m Roles")
dataset.Role.unique()

Dataset contains data of 4 Roles

array(['Batsman', 'All-Rounder', 'Bowler', 'Wicket Keeper'], dtype=object)

In [16]:
print(f"Dataset contains data of \033[1m{dataset.Team.unique().size}\033[0m Teams")
dataset.Team.unique()

Dataset contains data of 15 Teams

array(['Sunrisers Hyderabad', 'Mumbai Indians', 'Gujarat Lions',
       'Kings XI Punjab', 'Royal Challengers Bangalore',
       'Kolkata Knight Riders', 'Gujarat Titans', 'Pune Warriors India',
       'Rajasthan Royals', 'Delhi Daredevils', 'Chennai Super Kings',
       'Rising Pune Supergiant', 'Delhi Capitals', 'Lucknow Super Giants',
       'Punjab Kings'], dtype=object)

In [17]:
print(f"Dataset contains data of \033[1m{dataset.Year.unique().size}\033[0m years")
dataset.Year.unique()

Dataset contains data of 10 years

array([2014, 2015, 2016, 2018, 2020, 2022, 2013, 2021, 2017, 2019])

In [18]:
dataset['Player Origin'].unique()

array(['Overseas', 'Indian'], dtype=object)

# **Exploratory Data Analysis**

# Total Amount Spent By Each Team Each Year

In [19]:
teams = dataset.Team.unique()
for team in teams:
    data = dataset[dataset['Team'] == team].groupby('Year')['Amount'].sum()
    fig = px.line(data, x = data.index, y = 'Amount', title = f"{team}'s spent amount", text=data.index)
    fig.update_traces(textposition="top right")
    fig.show()

# Line Chart of different teams for comparision

In [20]:
data = pd.DataFrame(dataset.groupby(['Team', 'Year'])['Amount'].sum()).reset_index()
fig = px.line(data, x='Year', y='Amount', color='Team', symbol='Team')
fig.update_layout(title_text = "Overall comparision of different countries")
fig.show()

# Overall Expense Each Year

In [21]:
data = dataset.groupby('Year')['Amount'].sum()
fig = px.line(data, x = data.index, y = 'Amount', title = "Overall Expense Each year", text=data.index)
fig.update_traces(textposition="top right")
fig.show()

# Most Expensive Player Each Year

In [22]:
data = []
for i in sorted(dataset.Year.unique()):
    df = pd.DataFrame(dataset.groupby('Year').get_group(i))
    df = df[df['Amount'] == df.Amount.max()]
    data.append([i, np.array(df["Player"]), np.array(df["Amount"])[0], np.array(df["Team"])[0]])
data = pd.DataFrame(data, columns=["Year", "Players", "Amount", "Team"])
fig = px.line(data, x = data.Year, y = data.Amount, title = "Most Expensive Player Each year", text=data.Players)
fig.update_traces(textposition="top right")
fig.show()
fig = go.Figure(data=[go.Table(header=dict(values=['Year', 'Player','Team', 'Amount']), cells=dict(values=[data.Year, data.Players, data.Team, data.Amount]))])
fig.show()

# Total Amount Spent on Player Based on There Role

In [23]:
roles = dataset.Role.unique()
for role in roles:
    data = dataset[dataset['Role'] == role].groupby('Year')['Amount'].sum()
    fig = px.line(data, x = data.index, y = 'Amount', title = f"Total Amount Spent on {role}'s", text=data.index)
    fig.update_traces(textposition="top right")
    fig.show()

# Overall comparision of different Roles

In [24]:
data = pd.DataFrame(dataset.groupby(['Role', 'Year'])['Amount'].sum()).reset_index()
fig = px.line(data, x='Year', y='Amount', color='Role', symbol='Role')
fig.update_layout(title_text = "Overall comparision of different Roles")
fig.show()

# Total Number of Players Sold Each Year Based on Role

In [25]:
years = dataset.Year.unique()
for year in sorted(years):
    data = dataset[dataset['Year'] == year]
    fig = px.histogram(data, x="Role", title = f"Count Plot Based on role for {year}")
    fig.show()